// ISO 3661-1 alpha-2
// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
export const iso36611Alpha2 = [
	"AF",
	"AL",
	"DZ",
	"AS",
	"AD",
	"AO",
	"AI",
	"AQ",
	"AG",
	"AR",
	"AM",
	"AW",
	"AU",
	"AT",
	"AZ",
	"BS",
	"BH",
	"BD",
	"BB",
	"BY",
	"BE",
	"BZ",
	"BJ",
	"BM",
	"BT",
	"BO",
	"BQ",
	"BA",
	"BW",
	"BV",
	"BR",
	"IO",
	"BN",
	"BG",
	"BF",
	"BI",
	"CV",
	"KH",
	"CM",
	"CA",
	"KY",
	"CF",
	"TD",
	"CL",
	"CN",
	"CX",
	"CC",
	"CO",
	"KM",
	"CD",
	"CG",
	"CK",
	"CR",
	"HR",
	"CU",
	"CW",
	"CY",
	"CZ",
	"CI",
	"DK",
	"DJ",
	"DM",
	"DO",
	"EC",
	"EG",
	"SV",
	"GQ",
	"ER",
	"EE",
	"SZ",
	"ET",
	"FK",
	"FO",
	"FJ",
	"FI",
	"FR",
	"GF",
	"PF",
	"TF",
	"GA",
	"GM",
	"GE",
	"DE",
	"GH",
	"GI",
	"GR",
	"GL",
	"GD",
	"GP",
	"GU",
	"GT",
	"GG",
	"GN",
	"GW",
	"GY",
	"HT",
	"HM",
	"VA",
	"HN",
	"HK",
	"HU",
	"IS",
	"IN",
	"ID",
	"IR",
	"IQ",
	"IE",
	"IM",
	"IL",
	"IT",
	"JM",
	"JP",
	"JE",
	"JO",
	"KZ",
	"KE",
	"KI",
	"KP",
	"KR",
	"KW",
	"KG",
	"LA",
	"LV",
	"LB",
	"LS",
	"LR",
	"LY",
	"LI",
	"LT",
	"LU",
	"MO",
	"MG",
	"MW",
	"MY",
	"MV",
	"ML",
	"MT",
	"MH",
	"MQ",
	"MR",
	"MU",
	"YT",
	"MX",
	"FM",
	"MD",
	"MC",
	"MN",
	"ME",
	"MS",
	"MA",
	"MZ",
	"MM",
	"NA",
	"NR",
	"NP",
	"NL",
	"NC",
	"NZ",
	"NI",
	"NE",
	"NG",
	"NU",
	"NF",
	"MK",
	"MP",
	"NO",
	"OM",
	"PK",
	"PW",
	"PS",
	"PA",
	"PG",
	"PY",
	"PE",
	"PH",
	"PN",
	"PL",
	"PT",
	"PR",
	"QA",
	"RO",
	"RU",
	"RW",
	"RE",
	"BL",
	"SH",
	"KN",
	"LC",
	"MF",
	"PM",
	"VC",
	"WS",
	"SM",
	"ST",
	"SA",
	"SN",
	"RS",
	"SC",
	"SL",
	"SG",
	"SX",
	"SK",
	"SI",
	"SB",
	"SO",
	"ZA",
	"GS",
	"SS",
	"ES",
	"LK",
	"SD",
	"SR",
	"SJ",
	"SE",
	"CH",
	"SY",
	"TW",
	"TJ",
	"TZ",
	"TH",
	"TL",
	"TG",
	"TK",
	"TO",
	"TT",
	"TN",
	"TM",
	"TC",
	"TV",
	"TR",
	"UG",
	"UA",
	"AE",
	"GB",
	"UM",
	"US",
	"UY",
	"UZ",
	"VU",
	"VE",
	"VN",
	"VG",
	"VI",
	"WF",
	"EH",
	"YE",
	"ZM",
	"ZW",
	"AX",
] as const;

export type iso36611Alpha2 = (typeof iso36611Alpha2)[number];

export const iso36611Alpha2Map = {
	AF: { displayName: "Afghanistan" },
	AL: { displayName: "Albania" },
	DZ: { displayName: "Algeria" },
	AS: { displayName: "American Samoa" },
	AD: { displayName: "Andorra" },
	AO: { displayName: "Angola" },
	AI: { displayName: "Anguilla" },
	AQ: { displayName: "Antarctica" },
	AG: { displayName: "Antigua and Barbuda" },
	AR: { displayName: "Argentina" },
	AM: { displayName: "Armenia" },
	AW: { displayName: "Aruba" },
	AU: { displayName: "Australia" },
	AT: { displayName: "Austria" },
	AZ: { displayName: "Azerbaijan" },
	BS: { displayName: "Bahamas (the)" },
	BH: { displayName: "Bahrain" },
	BD: { displayName: "Bangladesh" },
	BB: { displayName: "Barbados" },
	BY: { displayName: "Belarus" },
	BE: { displayName: "Belgium" },
	BZ: { displayName: "Belize" },
	BJ: { displayName: "Benin" },
	BM: { displayName: "Bermuda" },
	BT: { displayName: "Bhutan" },
	BO: { displayName: "Bolivia (Plurinational State of)" },
	BQ: { displayName: "Bonaire, Sint Eustatius and Saba" },
	BA: { displayName: "Bosnia and Herzegovina" },
	BW: { displayName: "Botswana" },
	BV: { displayName: "Bouvet Island" },
	BR: { displayName: "Brazil" },
	IO: { displayName: "British Indian Ocean Territory (the)" },
	BN: { displayName: "Brunei Darussalam" },
	BG: { displayName: "Bulgaria" },
	BF: { displayName: "Burkina Faso" },
	BI: { displayName: "Burundi" },
	CV: { displayName: "Cabo Verde" },
	KH: { displayName: "Cambodia" },
	CM: { displayName: "Cameroon" },
	CA: { displayName: "Canada" },
	KY: { displayName: "Cayman Islands (the)" },
	CF: { displayName: "Central African Republic (the)" },
	TD: { displayName: "Chad" },
	CL: { displayName: "Chile" },
	CN: { displayName: "China" },
	CX: { displayName: "Christmas Island" },
	CC: { displayName: "Cocos (Keeling) Islands (the)" },
	CO: { displayName: "Colombia" },
	KM: { displayName: "Comoros (the)" },
	CD: { displayName: "Congo (the Democratic Republic of the)" },
	CG: { displayName: "Congo (the)" },
	CK: { displayName: "Cook Islands (the)" },
	CR: { displayName: "Costa Rica" },
	HR: { displayName: "Croatia" },
	CU: { displayName: "Cuba" },
	CW: { displayName: "Curaçao" },
	CY: { displayName: "Cyprus" },
	CZ: { displayName: "Czechia" },
	CI: { displayName: "Côte d'Ivoire" },
	DK: { displayName: "Denmark" },
	DJ: { displayName: "Djibouti" },
	DM: { displayName: "Dominica" },
	DO: { displayName: "Dominican Republic (the)" },
	EC: { displayName: "Ecuador" },
	EG: { displayName: "Egypt" },
	SV: { displayName: "El Salvador" },
	GQ: { displayName: "Equatorial Guinea" },
	ER: { displayName: "Eritrea" },
	EE: { displayName: "Estonia" },
	SZ: { displayName: "Eswatini" },
	ET: { displayName: "Ethiopia" },
	FK: { displayName: "Falkland Islands (the) [Malvinas]" },
	FO: { displayName: "Faroe Islands (the)" },
	FJ: { displayName: "Fiji" },
	FI: { displayName: "Finland" },
	FR: { displayName: "France" },
	GF: { displayName: "French Guiana" },
	PF: { displayName: "French Polynesia" },
	TF: { displayName: "French Southern Territories (the)" },
	GA: { displayName: "Gabon" },
	GM: { displayName: "Gambia (the)" },
	GE: { displayName: "Georgia" },
	DE: { displayName: "Germany" },
	GH: { displayName: "Ghana" },
	GI: { displayName: "Gibraltar" },
	GR: { displayName: "Greece" },
	GL: { displayName: "Greenland" },
	GD: { displayName: "Grenada" },
	GP: { displayName: "Guadeloupe" },
	GU: { displayName: "Guam" },
	GT: { displayName: "Guatemala" },
	GG: { displayName: "Guernsey" },
	GN: { displayName: "Guinea" },
	GW: { displayName: "Guinea-Bissau" },
	GY: { displayName: "Guyana" },
	HT: { displayName: "Haiti" },
	HM: { displayName: "Heard Island and McDonald Islands" },
	VA: { displayName: "Holy See (the)" },
	HN: { displayName: "Honduras" },
	HK: { displayName: "Hong Kong" },
	HU: { displayName: "Hungary" },
	IS: { displayName: "Iceland" },
	IN: { displayName: "India" },
	ID: { displayName: "Indonesia" },
	IR: { displayName: "Iran (Islamic Republic of)" },
	IQ: { displayName: "Iraq" },
	IE: { displayName: "Ireland" },
	IM: { displayName: "Isle of Man" },
	IL: { displayName: "Israel" },
	IT: { displayName: "Italy" },
	JM: { displayName: "Jamaica" },
	JP: { displayName: "Japan" },
	JE: { displayName: "Jersey" },
	JO: { displayName: "Jordan" },
	KZ: { displayName: "Kazakhstan" },
	KE: { displayName: "Kenya" },
	KI: { displayName: "Kiribati" },
	KP: { displayName: "Korea (the Democratic People's Republic of)" },
	KR: { displayName: "Korea (the Republic of)" },
	KW: { displayName: "Kuwait" },
	KG: { displayName: "Kyrgyzstan" },
	LA: { displayName: "Lao People's Democratic Republic (the)" },
	LV: { displayName: "Latvia" },
	LB: { displayName: "Lebanon" },
	LS: { displayName: "Lesotho" },
	LR: { displayName: "Liberia" },
	LY: { displayName: "Libya" },
	LI: { displayName: "Liechtenstein" },
	LT: { displayName: "Lithuania" },
	LU: { displayName: "Luxembourg" },
	MO: { displayName: "Macao" },
	MG: { displayName: "Madagascar" },
	MW: { displayName: "Malawi" },
	MY: { displayName: "Malaysia" },
	MV: { displayName: "Maldives" },
	ML: { displayName: "Mali" },
	MT: { displayName: "Malta" },
	MH: { displayName: "Marshall Islands (the)" },
	MQ: { displayName: "Martinique" },
	MR: { displayName: "Mauritania" },
	MU: { displayName: "Mauritius" },
	YT: { displayName: "Mayotte" },
	MX: { displayName: "Mexico" },
	FM: { displayName: "Micronesia (Federated States of)" },
	MD: { displayName: "Moldova (the Republic of)" },
	MC: { displayName: "Monaco" },
	MN: { displayName: "Mongolia" },
	ME: { displayName: "Montenegro" },
	MS: { displayName: "Montserrat" },
	MA: { displayName: "Morocco" },
	MZ: { displayName: "Mozambique" },
	MM: { displayName: "Myanmar" },
	NA: { displayName: "Namibia" },
	NR: { displayName: "Nauru" },
	NP: { displayName: "Nepal" },
	NL: { displayName: "Netherlands (the)" },
	NC: { displayName: "New Caledonia" },
	NZ: { displayName: "New Zealand" },
	NI: { displayName: "Nicaragua" },
	NE: { displayName: "Niger (the)" },
	NG: { displayName: "Nigeria" },
	NU: { displayName: "Niue" },
	NF: { displayName: "Norfolk Island" },
	MK: { displayName: "North Macedonia" },
	MP: { displayName: "Northern Mariana Islands (the)" },
	NO: { displayName: "Norway" },
	OM: { displayName: "Oman" },
	PK: { displayName: "Pakistan" },
	PW: { displayName: "Palau" },
	PS: { displayName: "Palestine, State of" },
	PA: { displayName: "Panama" },
	PG: { displayName: "Papua New Guinea" },
	PY: { displayName: "Paraguay" },
	PE: { displayName: "Peru" },
	PH: { displayName: "Philippines (the)" },
	PN: { displayName: "Pitcairn" },
	PL: { displayName: "Poland" },
	PT: { displayName: "Portugal" },
	PR: { displayName: "Puerto Rico" },
	QA: { displayName: "Qatar" },
	RO: { displayName: "Romania" },
	RU: { displayName: "Russian Federation (the)" },
	RW: { displayName: "Rwanda" },
	RE: { displayName: "Réunion" },
	BL: { displayName: "Saint Barthélemy" },
	SH: { displayName: "Saint Helena, Ascension and Tristan da Cunha" },
	KN: { displayName: "Saint Kitts and Nevis" },
	LC: { displayName: "Saint Lucia" },
	MF: { displayName: "Saint Martin (French part)" },
	PM: { displayName: "Saint Pierre and Miquelon" },
	VC: { displayName: "Saint Vincent and the Grenadines" },
	WS: { displayName: "Samoa" },
	SM: { displayName: "San Marino" },
	ST: { displayName: "Sao Tome and Principe" },
	SA: { displayName: "Saudi Arabia" },
	SN: { displayName: "Senegal" },
	RS: { displayName: "Serbia" },
	SC: { displayName: "Seychelles" },
	SL: { displayName: "Sierra Leone" },
	SG: { displayName: "Singapore" },
	SX: { displayName: "Sint Maarten (Dutch part)" },
	SK: { displayName: "Slovakia" },
	SI: { displayName: "Slovenia" },
	SB: { displayName: "Solomon Islands" },
	SO: { displayName: "Somalia" },
	ZA: { displayName: "South Africa" },
	GS: { displayName: "South Georgia and the South Sandwich Islands" },
	SS: { displayName: "South Sudan" },
	ES: { displayName: "Spain" },
	LK: { displayName: "Sri Lanka" },
	SD: { displayName: "Sudan (the)" },
	SR: { displayName: "Suriname" },
	SJ: { displayName: "Svalbard and Jan Mayen" },
	SE: { displayName: "Sweden" },
	CH: { displayName: "Switzerland" },
	SY: { displayName: "Syrian Arab Republic (the)" },
	TW: { displayName: "Taiwan (Province of China)" },
	TJ: { displayName: "Tajikistan" },
	TZ: { displayName: "Tanzania, the United Republic of" },
	TH: { displayName: "Thailand" },
	TL: { displayName: "Timor-Leste" },
	TG: { displayName: "Togo" },
	TK: { displayName: "Tokelau" },
	TO: { displayName: "Tonga" },
	TT: { displayName: "Trinidad and Tobago" },
	TN: { displayName: "Tunisia" },
	TM: { displayName: "Turkmenistan" },
	TC: { displayName: "Turks and Caicos Islands (the)" },
	TV: { displayName: "Tuvalu" },
	TR: { displayName: "Türkiye" },
	UG: { displayName: "Uganda" },
	UA: { displayName: "Ukraine" },
	AE: { displayName: "United Arab Emirates (the)" },
	GB: {
		displayName: "United Kingdom of Great Britain and Northern Ireland (the)",
	},
	UM: { displayName: "United States Minor Outlying Islands (the)" },
	US: { displayName: "United States of America (the)" },
	UY: { displayName: "Uruguay" },
	UZ: { displayName: "Uzbekistan" },
	VU: { displayName: "Vanuatu" },
	VE: { displayName: "Venezuela (Bolivarian Republic of)" },
	VN: { displayName: "Viet Nam" },
	VG: { displayName: "Virgin Islands (British)" },
	VI: { displayName: "Virgin Islands (U.S.)" },
	WF: { displayName: "Wallis and Futuna" },
	EH: { displayName: "Western Sahara*" },
	YE: { displayName: "Yemen" },
	ZM: { displayName: "Zambia" },
	ZW: { displayName: "Zimbabwe" },
	AX: { displayName: "Åland Islands" },
} as const satisfies Record<iso36611Alpha2, { displayName: string }>;
